while wait() do
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Water bowl",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
 
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Blood Curse",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Skateboard",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Blade Kagenou",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Orb Shadow",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Orb Rainbow",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Fire Curse",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Tail Dinosaur",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Orb Dragon",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Camera",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Cane",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Cake",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Grimoire",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Orb Beast",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Heart Demon",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Candy Pumpkin",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394
 
local args = {
    [1] = "Change",
    [2] = "Fish",
    [3] = "Backpack"
}
 
game:GetService("ReplicatedStorage").Inventory:FireServer(unpack(args))
 
end
